project:
  type: website
  output-dir: docs

website:
  title: "Envinformatics"
  navbar:
    background: primary
    search: true
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: Materia
    css: styles.css



